                <div class="row">
			<div class="col-xs-12">
			<img src="<?php echo $this->baseUrl.'/image/cabesa.png'?>">
			</div>
		</div>
		<div class="row" style="margin-bottom: 20px;">
			<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
				     <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

						<ol class="carousel-indicators">
                                                  <?php
                                                  $count=0;
                                                  foreach ($this->Datos as $row):
                                                  $count++;
                                                  if($count==1){
                                                  ?>
						  <li data-target="#carousel-example-generic" data-slide-to="<?php echo $count?>" class="active"></li>
						  <?php }else{?>
                                                  <li data-target="#carousel-example-generic" data-slide-to="<?php echo $count?>" ></li>
                                                  <?php } endforeach;?>
						</ol>
						<div class="carousel-inner">
                                                  <?php
                                                  $count=0;
                                                  foreach ($this->Datos as $row):
                                                  $count++;
                                                  $url=str_replace(' ','-',$row['titulo']);
                                                  if($count==1){
                                                  ?>
						  <div class="item active">
							<a href="<?php echo $this->baseUrl.'/ver/'.$url.'-'.$row['id_post'].'.html'?>"><img  src="<?php echo $this->baseUrl.'/'.$row['imagen']?>"></a>
						  </div>
                                                  <?php }else{?>
						  <div class="item">
							<a href="<?php echo $this->baseUrl.'/ver/'.$url.'-'.$row['id_post'].'.html'?>"><img  src="<?php echo $this->baseUrl.'/'.$row['imagen']?>"></a>
						  </div>
                                                  <?php } endforeach;?>
						</div>
						<a class="left carousel-control" href="examples/theme/#carousel-example-generic" role="button" data-slide="prev">
						  <span class="glyphicon glyphicon-chevron-left"></span>
						</a>
						<a class="right carousel-control" href="examples/theme/#carousel-example-generic" role="button" data-slide="next">
						  <span class="glyphicon glyphicon-chevron-right"></span>
						</a>
					</div>
			</div>
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" >
                            <center>

                              <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fzonanormal&amp;width=250&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100%; height:290px;" allowTransparency="true"></iframe>
                            </center>
			</div>

		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            <?php foreach ($this->rand as $row):
                                    $url=str_replace(' ','-',$row['titulo']);
                            ?>
                            <a href="<?php echo $this->baseUrl.'/ver/'.$url.'-'.$row['id_post'].'.html'?>"><img  style="width:100%" src="<?php echo $this->baseUrl.'/'.$row['imagen']?>" class="img-circle"></a>
                            <p><?php echo $row['descripcion']?></p>
                            <?php endforeach;?>
                        </div>

			<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                            <?php foreach ($this->Datos as $row):
                                    $url=str_replace(' ','-',$row['titulo']);
                            ?>
                            <div class="row">
                             <div class="col-xs-4">
                                 <a href="<?php echo $this->baseUrl.'/ver/'.$url.'-'.$row['id_post'].'.html'?>"><img  style="width:100%" src="<?php echo $this->baseUrl.'/'.$row['imagen']?>" ></a>
                             </div>
                             <div class="col-xs-8">
                                 <div class="recuadro-title"><?php echo $row['titulo']?></div>
                                 <div class="recuadro-desc">
                                     <?php echo $row['descripcion']?>
                                 </div>
                             </div>
                            </div>
                            <?php endforeach;?>
                        </div>
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                        <center>
                        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- lateral-grande -->
                        <ins class="adsbygoogle"
                             style="display:inline-block;width:300px;height:600px"
                             data-ad-client="ca-pub-3567481747949009"
                             data-ad-slot="7143929578"></ins>
                        <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                        </center>
                        </div>
		</div>
		<div class="row">

		</div>