<div class="row" style="margin-bottom: 40px;">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8">
        <img src="<?php echo $this->baseUrl.'/image/cabesa.png'?>">
        </div>
</div>
<div class="row" style="margin-bottom: 20px;">

        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <h1>
                Mi titulo que les parece
            </h1>
            <img src="<?php echo $this->baseUrl.'/uploads/descarga.jpg'?>">
            <div>
                hola como estan mis queridos amigos este es un post detallado
            </div>
                 
                            <div style="background: url(<?php echo $this->baseUrl?>/image/com.png) no-repeat 2px;margin-top: 15px;padding-left: 22px;" class="titlee"><h3>ayudame con un consejo : 
                                (<spam class="fb-comments-count" data-href="http://tusconfesiones.com/ver/<?php echo $url.'-'.$row['id_confecion'].'.html';?>" fb-xfbml-state="rendered"></spam>)</h3>
                            </div>
                            <div class="fb-comments fb_iframe_widget" data-href="http://tusconfesiones.com/ver/<?php echo $url.'-'.$row['id_confecion'].'.html';?>" data-num-posts="20"  data-width="100%"  data-mobile="false" fb-xfbml-state="rendered">
                            </div>

        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" >
            <div style="background-color:#000;height:110px">11</div>
            <div style="background-color:#000;height:110px">11</div>
        </div>

</div>




           