<div class="row" style="margin-bottom: 40px;">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8">
        <img src="<?php echo $this->baseUrl.'/image/cabesa.png'?>">
        </div>
</div>
<div class="row" style="margin-bottom: 20px;">

            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">


                <form  role="form" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl.'/post/guardar'?>">
            <div class="form-group">
            <label for="exampleInputEmail1">Titulo</label>
            <input type="text" name="Titulo" class="form-control" id="inputSuccess4" placeholder="Ingrese Titulo">
            </div>
            <select name="Categoria"class="form-control">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
            <div class="form-group">
            <label for="exampleInputPassword1">Descripción</label>
            <textarea name="Descripcion"class="form-control" rows="10"></textarea>
            </div>
            <div class="form-group">
            <label for="exampleInputPassword1">Pais</label>
            <select name="pais" id="pais" class="form-control">
              <option value="1">Seleccionar</option>
              <option value="1">Peru</option>
            </select>
            </div>
            <div class="form-group">
            <label for="exampleInputPassword1">Región</label>
            <select name="region" id="region" class="form-control">
              <option value="1">Seleccionar</option>
            </select>
            </div>
            <div class="form-group">
            <label for="exampleInputPassword1">Provincia</label>
            <select name="provincia" id="provincia" class="form-control">
              <option value="1">Seleccionar</option>
            </select>
            </div>
            <div class="form-group">
            <label for="exampleInputPassword1">Distrito</label>
            <select name="distrito" id="distrito" class="form-control">
              <option value="1">Seleccionar</option>
            </select>
            </div>
            <div class="form-group">
            <label for="exampleInputFile">Subir Imagen</label>
            <input type="file" name="File" id="exampleInputFile">
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" >
                        <center>
                        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- lateral-grande -->
                        <ins class="adsbygoogle"
                             style="display:inline-block;width:300px;height:600px"
                             data-ad-client="ca-pub-3567481747949009"
                             data-ad-slot="7143929578"></ins>
                        <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                        </center>
        </div>

</div>

            

                
           