<div class="row" style="margin-bottom: 40px;">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8">
        <img src="<?php echo $this->baseUrl.'/image/cabesa.png'?>">
        </div>
</div>
<div class="row" style="margin-bottom: 20px;">

            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">


                <form  role="form" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl.'/post/guardar'?>">
            <div class="form-group">
            <label for="exampleInputEmail1">Titulo</label>
            <input type="text" name="Titulo" class="form-control" id="inputSuccess4" placeholder="Ingrese Titulo">
            </div>
            <select name="Categoria"class="form-control">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
            <div class="form-group">
            <label for="exampleInputPassword1">Descripción</label>
            <textarea name="Descripcion"class="form-control" rows="10"></textarea>
            </div>
            <div class="form-group">
            <label for="exampleInputFile">Subir Imagen</label>
            <input type="file" name="File" id="exampleInputFile">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" >
                <div style="background-color:#000;height:110px">11</div>
                <div style="background-color:#000;height:110px">11</div>
        </div>

</div>

            

                
           