
<!DOCTYPE html>
<!-- saved from url=(0039)examples/theme/ -->
<html lang="en" class=""><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>HoyTevi - Neurus</title>
    
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl.'/'?>css/font-awesome.min.css" />
    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://getbootstrap.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/theme/theme.css" rel="stylesheet">
    <script language="javascript" src="http://www.jose-aguilar.com/scripts/jquery/combos_dependientes/js/jquery-1.2.6.min.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<!-- localizacion -->
<link href="<?php echo $this->baseUrl?>/css/style.css" rel="stylesheet">
	<script src="http://j.maxmind.com/app/geoip.js"></script>
	<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
        

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php echo $this->render('js.phtml'); ?>
</head>

  <body role="document" onload="getGeo()" style="background-image:url(http://www.elclubdelprogramador.com//wp-content/themes/averin/sprites/textures/waves-texture.png) !important;">

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="<?php echo $this->baseUrl?>">Hoytevi</a>
        </div>
        <div class="navbar-collapse collapse" style="height: 1px;">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->baseUrl?>">Home</a></li>
            <li><a href="<?php echo $this->baseUrl?>">About</a></li>
            <li><a href="<?php echo $this->baseUrl?>">Contact</a></li>

            </ul>

     <ul class="nav navbar-nav navbar-right">
        <?php
        // verificamos si existe sesion
        if(!isset($this->Info)){?>
         <li><a href="<?php echo $this->baseUrl.'/user/registro'?>" >Registro</a></li>
         <form class="navbar-form navbar-left" role="search" method="post" action="<?php echo $this->baseUrl?>/user/logueo">
            <div class="form-group">
              <input type="text" name="txtAlias" class="form-control" placeholder="usuario">
            </div>
            <div class="form-group">
              <input type="text" name="txtPassword"class="form-control" placeholder="password">
            </div>
            <button type="submit" class="btn btn-default">Ingresar</button>
          </form>
         <?php }else{ ?>
         <?php  foreach($this->Info as $row): ?>
        <li class="dropdown" style="background-color: #000">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">User:<?php echo $row['nombre']?> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <?php if($row['rol']=="admin"){?>
            <li><a href="<?php echo $this->baseUrl.'/user/admin'?>">Administrar</a></li>
            <?php } ?>
            <li><a href="<?php echo $this->baseUrl.'/post'?>">Nuevo Post</a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->baseUrl?>/user/logout">Salir</a></li>
          </ul>
        </li>
         <?php endforeach;?>
        
       <?php  }?>
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <!-- container -->
    <div class="container theme-showcase" role="main">
        <?php echo $this->layout()->content; ?>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?php echo $this->baseUrl?>/js/jquery.min.js"></script>
    <script src="<?php echo $this->baseUrl?>/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->baseUrl?>/js/docs.min.js"></script>

<footer class="content-info" role="contentinfo" style="display: block;">
  <div class="container">



  <hr>
  <div class="sotto-footer">


   <p class="copyright"><a href="/en/privacy/">Privacy and legal notes</a> - © 2014 </p>


  </div>

  </div>
</footer>



</body>
</html>

