
<!DOCTYPE html>
<!-- saved from url=(0039)examples/theme/ -->
<html lang="en" class=""><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Theme Template for Bootstrap</title>
    <link href="<?php echo $this->baseUrl?>/css/style.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl.'/'?>css/font-awesome.min.css" />
    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://getbootstrap.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/theme/theme.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="./index_files/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="./index_files/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<!-- localizacion -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script src="<?php echo $this->baseUrl?>/js/login.js"></script>
	<script src="http://j.maxmind.com/app/geoip.js"></script>
	<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
        
	<script type="text/javascript" >

	function getGeo(){

	if (navigator && navigator.geolocation) {
	   navigator.geolocation.getCurrentPosition(geoOK, geoKO);
	} else {
	   geoMaxmind();
	}

	}

	function geoOK(position) {
	showLatLong(position.coords.latitude, position.coords.longitude);
	}


	function geoMaxmind() {
	showLatLong(geoip_latitude(), geoip_longitude());
	}

	function geoKO(err) {
	if (err.code == 1) {
	error('El usuario ha denegado el permiso para obtener informacion de ubicacion.');
	} else if (err.code == 2) {
	error('Tu ubicacion no se puede determinar.');
	} else if (err.code == 3) {
	error('TimeOut.')
	} else {
	error('No sabemos que pasó pero ocurrio un error.');
	}
	}

	function showLatLong(lat, longi) {
	var geocoder = new google.maps.Geocoder();
	var yourLocation = new google.maps.LatLng(lat, longi);
	geocoder.geocode({ 'latLng': yourLocation },processGeocoder);

	}
	function processGeocoder(results, status){

	if (status == google.maps.GeocoderStatus.OK) {
	if (results[0]) {
	document.forms[0].dir.value=results[0].formatted_address;
	} else {
	error('Google no retorno resultado alguno.');
	}
	} else {
	error("Geocoding fallo debido a : " + status);
	}
	}
	function error(msg) {
	alert(msg);
	}
	</script>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    <style id="holderjs-style" type="text/css"></style><link type="text/css" rel="stylesheet" charset="UTF-8" href="./index_files/translateelement.css"><script type="text/javascript" charset="UTF-8" src="./index_files/main_es.js"></script><script type="text/javascript" charset="UTF-8" src="./index_files/element_main.js"></script></head>

  <body role="document" onload="getGeo()">

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="<?php echo $this->baseUrl?>">Hoytevi</a>
        </div>
        <div class="navbar-collapse collapse" style="height: 1px;">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->baseUrl?>">Home</a></li>
            <li><a href="<?php echo $this->baseUrl?>">About</a></li>
            <li><a href="<?php echo $this->baseUrl?>">Contact</a></li>
            <li class="dropdown">
              <a href="examples/theme/#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="examples/theme/#">Action</a></li>
                <li><a href="examples/theme/#">Another action</a></li>
                <li><a href="examples/theme/#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="examples/theme/#">Separated link</a></li>
                <li><a href="examples/theme/#">One more separated link</a></li>
              </ul>
            </li>
            </ul>

     <ul class="nav navbar-nav navbar-right">
        <?php
        // verificamos si existe sesion
        if(!isset($this->Info)){?>
         <form class="navbar-form navbar-left" role="search" method="post" action="<?php echo $this->baseUrl?>/user/logueo">
            <div class="form-group">
              <input type="text" name="txtAlias" class="form-control" placeholder="usuario">
            </div>
            <div class="form-group">
              <input type="text" name="txtPassword"class="form-control" placeholder="password">
            </div>
            <button type="submit" class="btn btn-default">Ingresar</button>
          </form>
         <?php }else{ ?>
         <?php  foreach($this->Info as $row): ?>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">User:<?php echo $row['nombre']?> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Mi cuenta</a></li>
            <li><a href="#">Mi portafolio</a></li>
            <li><a href="#">Nuevo Post</a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->baseUrl?>/user/logout">Salir</a></li>
          </ul>
        </li>
         <?php endforeach;?>
        </ul>
       <?php  }?>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <!-- container -->
    <div class="container theme-showcase" role="main">
        <?php echo $this->layout()->content; ?>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="<?php echo $this->baseUrl?>/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->baseUrl?>/js/docs.min.js"></script>

<footer class="content-info" role="contentinfo" style="display: block;">
  <div class="container">

   <div class="row">
	   <div class="col-sm-5">
	   <h5>Riot Design <small>Web &amp; Graphic Design Agency</small></h5>
	  <p>Via Jacopo Carrucci, 152  - 50053 Empoli (FI) <br>
		   +39 0571 711155 - info@riotdesign.eu<br></p>

		<div id="fb-root"></div>
<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Friotdesign.eu&amp;width=300&amp;height=21&amp;colorscheme=light&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;send=false&amp;appId=126287497453248" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:21px;" allowtransparency="true"></iframe>

	   </div>
	   <div class="col-sm-5">

	   <h5>From the Blog<sup>Rd</sup></h5>
						<a href="/en/2014/04/10/wearable-technologies-revolutionary-tools-and-ludicrous-gadgets/">Wearable technologies: revolutionary tools and ludicrous gadgets</a>
		<p>The recent technological history has accustomed us to witness epochal changes that arise quietly and soon invade our lives, changing … <a href="http://riotdesign.eu/en/2014/04/10/wearable-technologies-revolutionary-tools-and-ludicrous-gadgets/">Continued</a></p>

	    	   </div>
	   <div class="col-sm-2 hidden-xs">
	   <img class="slogan pull-right" src="/assets/img/che-il-buon-design-regni-sul-web.png" alt="May good design rule the Web" width="170" height="180">
	   </div>


   </div>

  <hr>
  <div class="sotto-footer">


  <div class="icone-social">
  <a href="http://www.facebook.com/riotdesign.eu" target="_blank" class="icona-facebook"> </a>
  <a href="http://twitter.com/riot_design_eu" target="_blank" class="icona-twitter"> </a>
  <a href="http://plus.google.com/100562758917063789241/" target="_blank" class="icona-google-plus"> </a>
  <a href="http://www.flickr.com/groups/1705479@N23/" target="_blank" class="icona-flickr"> </a>
  <a href="http://instagram.com/riot_design" target="_blank" class="icona-instagram"> </a>
  </div>

   <p class="copyright"><a href="/en/privacy/">Privacy and legal notes</a> - © 2014 Riot Design</p>

     <div class="language_list"><ul><li><span>English</span></li><li><a class="noajax" href="http://riotdesign.eu/home/"><span>Italiano</span></a></li></ul></div>
  </div>

  </div>
</footer>
</body>
</html>

