		<div class="row">
			<div class="col-xs-12">
			<img src="<?php echo $this->baseUrl.'/image/cabesa.png'?>">
			</div>
		</div>
		<div class="row" style="margin-bottom: 20px;">
			<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
				     <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
						  <li data-target="#carousel-example-generic" data-slide-to="0" class=""></li>
						  <li data-target="#carousel-example-generic" data-slide-to="1" class="active"></li>
						  <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
						  <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
						</ol>
						<div class="carousel-inner">
						  <div class="item">
							<img data-src="holder.js/1140x500/auto/#777:#555/text:First slide" alt="First slide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMTQwIiBoZWlnaHQ9IjUwMCI+PHJlY3Qgd2lkdGg9IjExNDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjNzc3Ij48L3JlY3Q+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iNTcwIiB5PSIyNTAiIHN0eWxlPSJmaWxsOiM1NTU7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LXNpemU6NzFweDtmb250LWZhbWlseTpBcmlhbCxIZWx2ZXRpY2Esc2Fucy1zZXJpZjtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj5GaXJzdCBzbGlkZTwvdGV4dD48L3N2Zz4=">
						  </div>
						  <div class="item active">
							<img data-src="holder.js/1140x500/auto/#666:#444/text:Second slide" alt="Second slide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMTQwIiBoZWlnaHQ9IjUwMCI+PHJlY3Qgd2lkdGg9IjExNDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjNjY2Ij48L3JlY3Q+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iNTcwIiB5PSIyNTAiIHN0eWxlPSJmaWxsOiM0NDQ7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LXNpemU6NzFweDtmb250LWZhbWlseTpBcmlhbCxIZWx2ZXRpY2Esc2Fucy1zZXJpZjtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj5TZWNvbmQgc2xpZGU8L3RleHQ+PC9zdmc+">
						  </div>
						  <div class="item">
							<img data-src="holder.js/1140x500/auto/#555:#333/text:Third slide" alt="Third slide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMTQwIiBoZWlnaHQ9IjUwMCI+PHJlY3Qgd2lkdGg9IjExNDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjNTU1Ij48L3JlY3Q+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iNTcwIiB5PSIyNTAiIHN0eWxlPSJmaWxsOiMzMzM7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LXNpemU6NzFweDtmb250LWZhbWlseTpBcmlhbCxIZWx2ZXRpY2Esc2Fucy1zZXJpZjtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj5UaGlyZCBzbGlkZTwvdGV4dD48L3N2Zz4=">
						  </div>
						  <div class="item">
							<img data-src="holder.js/1140x500/auto/#555:#333/text:jesu" alt="forth" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMTQwIiBoZWlnaHQ9IjUwMCI+PHJlY3Qgd2lkdGg9IjExNDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjNTU1Ij48L3JlY3Q+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iNTcwIiB5PSIyNTAiIHN0eWxlPSJmaWxsOiMzMzM7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LXNpemU6NzFweDtmb250LWZhbWlseTpBcmlhbCxIZWx2ZXRpY2Esc2Fucy1zZXJpZjtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj5UaGlyZCBzbGlkZTwvdGV4dD48L3N2Zz4=">
						  </div>
						</div>
						<a class="left carousel-control" href="examples/theme/#carousel-example-generic" role="button" data-slide="prev">
						  <span class="glyphicon glyphicon-chevron-left"></span>
						</a>
						<a class="right carousel-control" href="examples/theme/#carousel-example-generic" role="button" data-slide="next">
						  <span class="glyphicon glyphicon-chevron-right"></span>
						</a>
					</div>
			</div>
			<div class="col-xs-12 col-sm-2 col-md-2 col-lg-2" >
				<div style="background-color:#000;height:110px">11</div>
				<div style="background-color:#000;height:110px">11</div>
			</div>
			<div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
				<div style="background-color:#000;height:110px">22</div>
				<div style="background-color:#000;height:110px">22</div>
			</div>

		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            <img  style="width:100%" src="<?php echo $this->baseUrl.'/image/a.jpg'?>" class="img-circle">
                            <p>Dada la gran cantidad de transacciones que se han experimentado en años anteriores, es probable que los cibercriminales aprovechen fechas como Cyber Perú Day para intentar obtener crédito económico.</p>
                            <img  style="width:100%" src="<?php echo $this->baseUrl.'/image/a.jpg'?>" class="img-circle">
                            <p>Dada la gran cantidad de transacciones que se han experimentado en años anteriores, es probable que los cibercriminales aprovechen fechas como Cyber Perú Day para intentar obtener crédito económico.</p>
                        </div>

			<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                            <div class="row">
                             <div class="col-xs-4">
                                 <img  style="width:100%" src="<?php echo $this->baseUrl.'/image/a.jpg'?>" >
                             </div>
                             <div class="col-xs-8">
                                 <div class="recuadro-title">Mi titulo</div>
                                 <div class="recuadro-desc">Esta es mi descripcion aber que te parece y que opinas
                                 Esta es mi descripcion aber que te parece y que opinas
                                 Esta es mi descripcion aber que te parece y que opinas Esta es mi descripcion aber que te parece y que opinas
                                 </div>
                             </div>
                            </div>
                        </div>
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="sidebar">

        <a class="sidebar-toggle" title="Expand Sidebar"><i class="icon-reorder"></i></a>

                <ul class="sidebar-content">
                        <li id="wpb-tabs-2" class="widget2 widget_wpb_tabs">
                            <ul class="wpb-tabs group tabs-4">
                                <li class="wpb-tab-recent"><a href="#tab-recent-2" title="Recent Posts" class="active"><i class="fa fa-clock-o"></i><span>Recent Posts</span></a></li>
                                <li class="wpb-tab-popular"><a href="#tab-popular-2" title="Most Popular" class=""><i class="fa fa-cog"></i><span>Most Popular</span></a></li>
                                <li class="wpb-tab-comments"><a href="#tab-comments-2" title="Comments" class=""><i class="fa fa-comments-o"></i><span>Comments</span></a></li>
                                <li class="wpb-tab-tags"><a href="#tab-tags-2" title="Tags" class=""><i class="fa fa-tags"></i><span>Tags</span></a></li>
                            </ul>
                            <ul id="tab-recent-2" class="list-recent wpb-tab" style="display: block;">
                                <?php foreach($this->Rand as $row):
                                        $url=str_replace(' ','-',$row['titulo']);
                                        ?>
                                <li class="format-image wpb-thumb-enabled group">
                                    <a title="<?php echo $row['titulo']?>" href="<?php echo $this->baseUrl.'/ver/'.$url.'-'.$row['id_confecion'].'.html'?>">
                                        <span class="wpb-thumb"><img width="100" height="100" src="<?php echo $this->baseUrl.'/'.$row['imagen']?>" class="attachment-size-thumbnail-tabs wp-post-image" /></span>
                                        <span class="wpb-text"><i class="title"><?php echo $row['titulo']?></i><i class="meta"><?php echo $row['fechaconfecion']?></i></span>
                                    </a>
                                </li>
                                <?php endforeach;?>
                            </ul>
                            <ul id="tab-popular-2" class="list-popular wpb-tab" style="display: none;">
                                <?php foreach($this->Ultimos as $row):
                                        $url=str_replace(' ','-',$row['titulo']);
                                        ?>
                                <li class="format-image wpb-thumb-enabled group">
                                    <a title="<?php echo $row['titulo']?>" href="<?php echo $this->baseUrl.'/ver/'.$url.'-'.$row['id_confecion'].'.html'?>">
                                        <span class="wpb-thumb"><img width="100" height="100" src="<?php echo $this->baseUrl.'/'.$row['imagen']?>" class="attachment-size-thumbnail-tabs wp-post-image" /></span>
                                        <span class="wpb-text"><i class="title"><?php echo $row['titulo']?></i><i class="meta"><?php echo $row['fechaconfecion']?></i></span>
                                    </a>
                                </li>
                                <?php endforeach;?>
                            </ul>
                            <ul id="tab-comments-2" class="list-comments wpb-tab" style="display: none;">
                                <?php foreach($this->UserInfo as $row):?>
                                <li class="group wpb-thumb-enabled">
                                    <a title="<?php echo $row['pseudonimo']?>" href="<?php echo $this->baseUrl.'/usuario/'.$row['pseudonimo']?>">
                                        <span class="wpb-thumb"><img alt="" src="<?php echo $this->baseUrl.'/'.$row['imagen']?>" class="avatar avatar-128 photo avatar-default" height="128" width="128"></span>
                                        <span class="wpb-text"><i class="meta"><?php echo $row['pseudonimo']?></i><i class="title">Nuevo Usuario</i></span>
                                    </a>
                                </li>
                                <?php endforeach;?>
                             </ul>
                            <ul id="tab-tags-2" class="list-tags wpb-tab" style="display: none;">
                                <li>
                                    <?php
                                    $i=0;
                                    foreach($this->ConfecionTag as $row):
                                            $url=str_replace(' ','-',$row['titulo']);
                                            $i++;
                                    if($i==40){break;}
                                            $rand1=mt_rand(8*10, 20*10) / 10;
                                            ?>
                                    <a href="<?php echo $this->baseUrl.'/ver/'.$url.'-'.$row['id_confecion'].'.html'?>" class="tag-link-178"  style="font-size: <?php echo $rand1?>pt;"><?php echo $row['titulo']?></a>
                                    <?php endforeach;?>
                                </li>
                            </ul>
                        </li>
                </ul>
        </div>

                        </div>
		</div>
		<div class="row">
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
			<div class="col-xs-1"> 1 </div>
		</div>

      <div class="page-header">
        <h1>Noticias Locales</h1>
      </div>

	<div class="jumbotron">
        <h2>Primera Opción</h2>
		<div><p>Detectando ciudad: con permiso del usuario </p>
		<form>
			<input type="text" name="dir" size="80">
		</form>
	</div>
		<h2>Segunda Opción</h2>
		<div><p>Detectando ciudad: sin permiso solo podemos saber el país</p>
		<script src="http://code.jquery.com/jquery-latest.js"></script>
			<script>
			$.getJSON('http://api.wipmania.com/jsonp?callback=?', function (data) {
			   $("#pais").html( data.address.country);
			});
			</script>
			<div id="pais" ></div>
		</div>
		<h2>Tercera Opción</h2>
		<div><p>ciudad del usuario registrado:
		<?php
		if($a=mysql_fetch_array($query)){
			echo $a['ciudad'];
		}
		?>
		</p></div>
      </div>
	  <!-- Button to trigger modal -->

