            <form  role="form" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl.'/user/registro'?>">
            <div class="form-group">
            <label for="exampleInputEmail1">Nombre</label>
            <input type="text" name="Nombre" class="form-control" id="inputSuccess4" placeholder="Ingrese Nombre">
            </div>
            <div class="form-group">
            <label for="exampleInputEmail1">Apellido</label>
            <input type="text" name="Apellido" class="form-control" id="inputSuccess4" placeholder="Ingrese Apellido">
            </div>
            <div class="form-group">
            <label for="exampleInputEmail1">Alias</label>
            <input type="text" name="Alias" class="form-control" id="inputSuccess4" placeholder="Ingrese Alias">
            </div>
            <div class="form-group">
            <label for="exampleInputEmail1">Contraseña</label>
            <input type="text" name="Password" class="form-control" id="inputSuccess4" placeholder="Ingrese Contraseña">
            </div>

            <select name="pais" id="pais" class="form-control">
              <option value="1">Seleccionar</option>
              <option value="1">Peru</option>
            </select>
            <select name="region" id="region" class="form-control">
              <option value="1">Seleccionar</option>
            </select>
            <select name="provincia" id="provincia" class="form-control">
              <option value="1">Seleccionar</option>
            </select>
            <select name="distrito" id="distrito" class="form-control">
              <option value="1">Seleccionar</option>
            </select>
            <div class="form-group">
            <label for="exampleInputFile">Imagen Perfil</label>
            <input type="file" name="File" id="exampleInputFile">
            </div>
            <button type="submit" name="submit" class="btn btn-default">Registrar</button>
            </form>